



<br>

# 예외

작성일자 : 2021-12-04

내용 : 토비스프링 4장 공부

<br><br>

- catch블록을 이용해 화면에 메시지를 출력하는 건 예외를 처리한 게 아니다.
- 예외를 처리할 때 반드시 지켜야할 핵심 원칙은 모든 예외를 적절하게 복구되든지 아니면 작업을 중단시키고 운영자 또는 개발자에게 분명하게 통보돼야 한다.



<br><br>

## 예외의 종류와 특징

자바에서 throw를 통해 발생시킬 수 있는 예외는 크게 세가지가 있다.

<img width="532" alt="20211204_152824_1" src="https://user-images.githubusercontent.com/56250078/144708812-4734d818-7630-42b0-8c92-4905e898fde5.png">

<br>

### 1. Error

- **java.lang.Error** 클래스의 서브클래스들

- 에러(Error)란 **컴퓨터 하드웨어의 오동작** 또는 **고장**으로 인해 응용프로그램에 이상이 생겼거나 JVM 실행에 문제가 생겼을 경우 발생하는 것

  따라서 **개발자가 미리 예측하여 처리할 수 없기 때문에,** 애플리케이션에서 오류에 대한 처리를 **신경 쓰지 않아도 된다.**

   https://java119.tistory.com/44

  **오류(Error 에러)- 시스템 레벨에서 발생**

  

- 에러는 시스템에 비정상적인 상황이 발생했을 경우에 사용

- 주로 자바 VM에서 발생시키고 애플리케이션 코드에서 잡으려고 하면 안 된다.
  catch 블록으로 잡아봤자 아무런 대응 방법이 없기 때문이다. 

- 예 ) OutOfMemoryError, ThreadDeath ....

<br>

### 2. 체크예외

- **java.lang.Exception **클래스의 서브클래스 이지만 RuntimeException을 상속하지 않은 클래스

- 체크 예외가 발생할 수 있는 메소드를 사용할 경우 **반드시** 예외를 처리하는 코드를 작성해야 한다.
  catch로 잡든지 throws로 던져야한다. 그렇지 않으면 컴파일 에러가 발생한다.

- 예) IOException, SQLException 등

  <br>

### 3. 언 체크 예외 or 런타임 예외

- 언체크 (unchecked exception)  : **java.lang.RuntimeException**을 상속한 클래스
- RuntimeException 클래스는 Exception의 서브클래스
- 예외 처리를 강제하지 않는다.
- 언 체크예외 혹은 런타임 예외라고도한다.
- 런타임예외는 주로 프로그램의 오류가 있을 때 발생하도록 의도됐다. 
  개발자의 부주의로 발생할 수 있는 경우에 발생하는 예외이다.
- 예 ) NullPointException - 오브젝트를 할당하지 않은 레퍼런스 변수를 사용할 때 발생
      , IllegalArgumentException - 허용되지 않는 값을 사용해서 메서드를 호출할 때 발생  

<br>

참고) 
체크예외가 예외처리를 강제하는 것 때문에 무책임한 throws가 남발됐다.
자바표준스펙 API들은 예상 가능한 예외상황을 다루는 예외를 체크예외로 만들지 않는 경향이 있기도 하다.

<br><br>



## 예외처리 방법

### 1. 예외 복구

- 예외 상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 것

- 예외로 인해 기본 작업 흐름이 불가능하면 다른 작업 흐름으로 자연스럽게 유도할 수도 있다.

- 예외가 처리 됐으면 비록 기능적으로는 사용자에게 예외상황으로 비쳐도 애플리케이션에서는 정상적으로 설계된 흐름을 따라 진행돼야 한다.

- 재시도가 의미가 있는 경우에는 최대 횟수만큼 반복적으로 시도함으로써 예외 상황에서 복구되게 할 수 있다.

- ```java
  // 재시도를 통해 예외를 복구하는 코드
  int mixretry = 5;
  while(mixretry --> 0){    // mixretry--; mixretry > 0; 이 두 가지를 합쳐놓은 것
      try {
          ...              // 예외가 발생할 가능성이 있는 시도
          return;          // 작업성공 
      }
      catch(SomeException e){
          // 로그 출력, 정해진 시간만큼 대기 예) Thread.sleep(초 입력);
      }
      finally{
          // 리소스 반납, 정리 작업
      }
  }
  throw new RetryFailedException(); // 최대 재시도 횟수를 넘기면 직접 예외를 발생
  ```

  

### 2. 예외 처리 회피

- throws문으로 선언해서 예외가 발생하면 알아서 던져지게 하거나 catch문으로 일단 예외를 잡은 후에 로그를 남기고 다시 예외를 던지는(rethrow)방법도 있다.

- 예외를 회피하는 것은 예외 복구처럼 의도가 분명해야한다. 긴밀한 관계에 있는 다른 오브젝트에게 예외처리 책임을 분명히 지게 하거나, 자신을 사용하는 쪽에서 예외를 다루는 게 최선의 방법이라는 분명한 확신이 있어야한다.

  

- 예외 처리 회피 1

  ```java
  public void add() throws SQLException{
      // JDBC API
  }
  ```

  

- 예외 처리 회피 2 (rethrow)

  ```java
  public void add() throws SQLException{
      try{
          // JDBC API
      }
      catch(SQLException e){
          //로그 출력
          throw e;
      }
  }
  ```

  

  

  생각해볼것 - SQLException
  JdbcContext나 JdbcTemplate이 사용하는 콜백오브젝트는 메소드 선언을 보면 ResultSet이나 PreparedStatement 등을 이용해서 작업하다 발생하는 SQLException을 자신이 처리하지 않고 템플릿으로 던져버린다. 콜백 오브젝트의 메소드는 SQLException에 대한 예외를 회피하고 템플릿 레벨에서 처리하도록 던져준다.







### 3. 예외 전환

- exception translation

- 발생한 예외를 그대로 넘기는 게 아니라 적절한 예외로 전환해서 던진다.

  ```java
  /*
  사용자 정보를 등록하려고 시도해보고, 만약 중복된 아이디 값 때문에 에러가 나는 경우에는 이를 확인해서 좀 더 의미 있는 DuplicatedKeyException으로 전환해주는 DAO 메서드의 예다.
  
  예외 전환 기능을 가진 DAO 메소드
  */
  
  public void add(User user) throws DuplicateUserIdException, SQLException {
      try{
          // JDBC를 이용해 user 정보를 DB에 추가하는 코드 또는 
          // 그런 기능을 가진 SQLException을 던지는 메소드를 호출하는 코드
      }
      catch(SQLException e){
          // ErrorCode가 MySQL의 "Duplicate Entry(1062)"이면 예외 전환
          if(e.getErrorCode() == MysqlErrorNumbers.ER_DUP_ENTRY){
              throw DuplicateUserIdException();
          }else{
              throw e; // 그 외의 경우는 SQLException 그대로
          }     
      }    
  }
  ```

  

- 방법 : 중첩예외(nested exception)
      중첩예외는 getCause() 메소드를 이용해서 처음 발생한 예외를 확인할 수 있다.
      initCause() 메소드로 근본 원인이 되는 예외를 넣어준다.

  ```java
  catch(SQLException e){
      ...
      throw DuplicateUserIdException(e);
      }   
  ```

  

  ```java
  catch(SQLException e){
      ...
      throw DuplicateUserIdException().initCause(e);
      }   
  ```

  

- **목적**

  1. 내부에서 발생한 예외를 그대로 던지는 것이 그 예외상황에 대한 적정한 의미를 부여해주지  못하는 경우 => **의미를 분명하게 해줄 수 있는 예외로 바꿔줘야 한다.**

  2. 예외를 처리하기 쉽고 단순하게 만들기 위해 포장(wrap)한다.

     중첩예외를 이용해 새로운 예외를 만들고 원인(cause)이 되는 예외를 내부에 담아서 던지는 방식이지만 의미를 명확하게 하려고 전환하는 게 아니라 **예외처리를 강제하는 체크 예외를 언체크예외인 런타임예외로 바꾸는 경우에 사용한다.**

     어짜피 복구가 불가능한 예외라면 가능한 빨리 런타임 예외로 포장해서 던지게 하는 하는 것이 다른 계층의 메소드를 작성할 때 불필요한 throws 선언이 들어가지 않도록 해줘야 한다.

     
     
     



























